### ISSUE TITLE
Save the date a book was read 

### ISSUE THREAD

**Issue by Airmagic** [JustinGJohnson/book_wishlist#1]

**Comment by justint1me** [comment]
1. Added date_read instance variable to Book class and set it to an empty string to start
2. pip3 install datetime in console
3. import datetime in datastore.py
4. comments for code at function set_read in datastore.py
5. Add date_read to template in __str__ method of Book class

**Comment by justint1me** [comment]
6. Need to add a string version of date_read instance variable to the list output in the for loop of make_output_data in datastore.py

**Comment by justint1me** [comment]
7. Also need to fill date_read with the data[4] when constructing a list form the file in datastore.py make_book_list function
