### ISSUE TITLE
Add the ability to delete a book from the wishlist

### ISSUE THREAD

**Issue by Airmagic** [JustinGJohnson/book_wishlist#2]
Delete a book from the list of unread books

**Comment by justint1me** [comment]
1. Add choice to delete book to function display_menu_get_choice in ui.py
2.  Add elif for new delete book choice to function handle_choice in wishlist.py
3. Create delete_book function in wishlist.py (no functionality yet)
4. add delete_book function to datastore.py to delete a list item from book_list that corresponds to id
