### ISSUE TITLE
Alert if a book that has been read, is added to the wishlist

### ISSUE THREAD

**Issue by Airmagic** [JustinGJohnson/book_wishlist#5]
Example: if user has added a book, then marked it as read; they will be permitted to add the same book to the wish list. You may want to let them add it again (maybe they want to read it again, or read a different edition) but the program should alert the user, and verify that they do want to add the same book again.

**Comment by justint1me** [comment]
Finished this just now. I made it alert the user for both read and unread books. I thought this made more sense than only alerting them if they want to re add a book just on the read list.
