### ISSUE TITLE
Save a rating or review of a book that has been read

### ISSUE THREAD

**Issue by Airmagic** [JustinGJohnson/book_wishlist#6]
Save ratings as stars our of 5; or thumbs up/thumbs down, or a text review, or something else?

**Comment by Airmagic** [comment]
Save ratings as stars our of 5; or thumbs up/thumbs down, or a text review, or something else?

**Comment by justint1me** [comment]
Starting working on this one earlier because it is not too different then my adding a date the book was read. Will be sometime today I commit and push.
